"""Export history: one row per generated deliverable.

When an operator exports a batch the file lands in ``exports/`` and a row is
written here.  Keeping the row (rather than only the file) lets the UI show
past exports with their size, row count and generating user, lets the API
re-serve a previous export without regenerating it, and gives the audit trail
a concrete artifact to point at.

Rows are never updated except for the terminal ``completed`` / ``failed``
transition; a re-export writes a new row with a fresh filename.
"""

from __future__ import annotations

from datetime import datetime
from typing import TYPE_CHECKING, Any

from sqlalchemy import JSON, ForeignKey, Integer, String, Text
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.database.base import Base, TimestampMixin, UTCDateTime
from app.models.enums import ExportFormat, ExportStatus
from app.models.types import enum_column

if TYPE_CHECKING:  # pragma: no cover - typing only
    from app.models.user import User


class ExportHistory(Base, TimestampMixin):
    """One export file that was (or is being) generated."""

    __tablename__ = "export_history"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    batch_id: Mapped[str | None] = mapped_column(String(36), nullable=True, index=True)
    batch_name: Mapped[str | None] = mapped_column(String(255), nullable=True)
    #: Correlates with the ``processing_jobs`` row when generated by a job.
    job_id: Mapped[int | None] = mapped_column(Integer, nullable=True, index=True)

    format: Mapped[ExportFormat] = mapped_column(
        enum_column(ExportFormat, "export_format"),
        nullable=False,
        default=ExportFormat.XLSX,
    )
    status: Mapped[ExportStatus] = mapped_column(
        enum_column(ExportStatus, "export_status"),
        nullable=False,
        default=ExportStatus.PENDING,
        index=True,
    )

    #: Name as served to the client (sanitised at generation time).
    filename: Mapped[str] = mapped_column(String(255), nullable=False)
    #: Path relative to ``exports/`` - never an absolute filesystem path.
    storage_path: Mapped[str | None] = mapped_column(String(1000), nullable=True)
    mime_type: Mapped[str | None] = mapped_column(String(100), nullable=True)
    byte_size: Mapped[int | None] = mapped_column(Integer, nullable=True)
    sha256: Mapped[str | None] = mapped_column(String(64), nullable=True)

    #: Material rows written into the file.
    row_count: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    #: Whether image files were bundled alongside (zip) the sheet.
    include_images: Mapped[bool] = mapped_column(nullable=False, default=False)

    error: Mapped[str | None] = mapped_column(Text, nullable=True)
    #: Free-form extras: worksheet name, column list, warnings, etc.
    detail: Mapped[dict[str, Any]] = mapped_column(JSON, nullable=False, default=dict)

    created_by_id: Mapped[int | None] = mapped_column(
        ForeignKey("users.id", ondelete="SET NULL"), nullable=True, index=True
    )
    #: When the operator asked for the export (``created_at`` is row insert).
    requested_at: Mapped[datetime | None] = mapped_column(UTCDateTime, nullable=True)
    completed_at: Mapped[datetime | None] = mapped_column(UTCDateTime, nullable=True)
    #: Optional expiry after which the file may be pruned from disk.
    expires_at: Mapped[datetime | None] = mapped_column(UTCDateTime, nullable=True)

    created_by: Mapped[User | None] = relationship(
        foreign_keys=[created_by_id], lazy="noload"
    )

    @property
    def is_available(self) -> bool:
        """``True`` when the artifact can still be served to a client."""
        return self.status == ExportStatus.COMPLETED and self.storage_path is not None

    def __str__(self) -> str:  # pragma: no cover - display helper
        return f"<ExportHistory {self.filename} {self.status}>"