"""initial schema

Revision ID: c29016606e83
Revises: 
Create Date: 2026-09-24 15:41:10.437978

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from app.database.base import UTCDateTime


# revision identifiers, used by Alembic.
revision: str = 'c29016606e83'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('manufacturers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=200), nullable=False),
    sa.Column('website', sa.String(length=500), nullable=True),
    sa.Column('search_domain', sa.String(length=255), nullable=True),
    sa.Column('image_url_template', sa.String(length=1000), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('created_at', UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_manufacturers')),
    sa.UniqueConstraint('name', name=op.f('uq_manufacturers_name')),
    sa.UniqueConstraint('slug', name=op.f('uq_manufacturers_slug'))
    )
    with op.batch_alter_table('manufacturers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_manufacturers_created_at'), ['created_at'], unique=False)

    op.create_table('materials',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('batch_id', sa.String(length=36), nullable=False),
    sa.Column('batch_name', sa.String(length=255), nullable=False),
    sa.Column('source_filename', sa.String(length=500), nullable=False),
    sa.Column('source_sheet', sa.String(length=255), nullable=False),
    sa.Column('row_number', sa.Integer(), nullable=False),
    sa.Column('material_code', sa.String(length=120), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('brand', sa.String(length=200), nullable=True),
    sa.Column('model', sa.String(length=200), nullable=True),
    sa.Column('category', sa.String(length=120), nullable=False),
    sa.Column('unit', sa.String(length=40), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('extra', sa.JSON(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'parsed', 'queued', 'searching', 'downloading', 'verifying', 'matched', 'needs_review', 'not_found', 'failed', 'skipped', name='material_status', native_enum=False, length=40), nullable=False),
    sa.Column('search_query', sa.Text(), nullable=True),
    sa.Column('search_query_hash', sa.String(length=64), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('image_count', sa.Integer(), nullable=False),
    sa.Column('accepted_image_id', sa.Integer(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('processed_at', UTCDateTime(timezone=True), nullable=True),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.Column('created_at', UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_materials')),
    sa.UniqueConstraint('batch_id', 'row_number', name='batch_row')
    )
    with op.batch_alter_table('materials', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_materials_accepted_image_id'), ['accepted_image_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_materials_batch_id'), ['batch_id'], unique=False)
        batch_op.create_index('ix_materials_batch_status', ['batch_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_materials_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_materials_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_materials_job_id'), ['job_id'], unique=False)
        batch_op.create_index('ix_materials_material_code', ['material_code'], unique=False)
        batch_op.create_index('ix_materials_search_query_hash', ['search_query_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_materials_status'), ['status'], unique=False)

    op.create_table('processing_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('timestamp', UTCDateTime(timezone=True), nullable=False),
    sa.Column('level', sa.Enum('debug', 'info', 'warning', 'error', 'critical', name='log_level', native_enum=False, length=20), nullable=False),
    sa.Column('logger', sa.String(length=200), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.Column('job_type', sa.String(length=40), nullable=True),
    sa.Column('material_id', sa.Integer(), nullable=True),
    sa.Column('batch_id', sa.String(length=36), nullable=True),
    sa.Column('provider', sa.String(length=60), nullable=True),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.Column('context', sa.JSON(), nullable=False),
    sa.Column('created_at', UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_processing_logs'))
    )
    with op.batch_alter_table('processing_logs', schema=None) as batch_op:
        batch_op.create_index('ix_processing_logs_batch', ['batch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_processing_logs_batch_id'), ['batch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_processing_logs_created_at'), ['created_at'], unique=False)
        batch_op.create_index('ix_processing_logs_job_created', ['job_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_processing_logs_job_id'), ['job_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_processing_logs_level'), ['level'], unique=False)
        batch_op.create_index('ix_processing_logs_level_created', ['level', 'created_at'], unique=False)
        batch_op.create_index('ix_processing_logs_material', ['material_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_processing_logs_material_id'), ['material_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_processing_logs_request_id'), ['request_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_processing_logs_timestamp'), ['timestamp'], unique=False)

    op.create_table('provider_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('provider', sa.String(length=60), nullable=False),
    sa.Column('provider_kind', sa.Enum('manufacturer', 'distributor', 'marketplace', 'web_search', 'image_search', 'internal', name='provider_kind', native_enum=False, length=40), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.Column('material_id', sa.Integer(), nullable=True),
    sa.Column('query', sa.Text(), nullable=True),
    sa.Column('outcome', sa.String(length=30), nullable=False),
    sa.Column('result_count', sa.Integer(), nullable=False),
    sa.Column('accepted_count', sa.Integer(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('error_type', sa.String(length=120), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('http_status', sa.Integer(), nullable=True),
    sa.Column('detail', sa.JSON(), nullable=False),
    sa.Column('started_at', UTCDateTime(timezone=True), nullable=False),
    sa.Column('finished_at', UTCDateTime(timezone=True), nullable=True),
    sa.Column('failure_streak', sa.Integer(), nullable=False),
    sa.Column('created_at', UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_provider_history'))
    )
    with op.batch_alter_table('provider_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_provider_history_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_provider_history_job_id'), ['job_id'], unique=False)
        batch_op.create_index('ix_provider_history_material', ['material_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_provider_history_material_id'), ['material_id'], unique=False)
        batch_op.create_index('ix_provider_history_outcome', ['outcome'], unique=False)
        batch_op.create_index(batch_op.f('ix_provider_history_provider'), ['provider'], unique=False)
        batch_op.create_index('ix_provider_history_provider_started', ['provider', 'started_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_provider_history_started_at'), ['started_at'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('viewer', 'reviewer', 'operator', 'admin', name='user_role', native_enum=False, length=40), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', UTCDateTime(timezone=True), nullable=True),
    sa.Column('created_at', UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email'))
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_created_at'), ['created_at'], unique=False)

    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('actor_email', sa.String(length=320), nullable=True),
    sa.Column('action', sa.Enum('login', 'login_failed', 'logout', 'token_refresh', 'user_created', 'user_updated', 'user_deactivated', 'password_changed', 'upload_created', 'job_started', 'job_paused', 'job_resumed', 'job_cancelled', 'job_retried', 'review_approved', 'review_rejected', 'image_accepted', 'image_rejected', 'export_created', 'settings_updated', 'api_key_updated', name='audit_action', native_enum=False, length=40), nullable=False),
    sa.Column('entity_type', sa.String(length=60), nullable=True),
    sa.Column('entity_id', sa.String(length=60), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.Column('context', sa.JSON(), nullable=False),
    sa.Column('created_at', UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name=op.f('fk_audit_logs_actor_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_action'), ['action'], unique=False)
        batch_op.create_index('ix_audit_logs_action_created', ['action', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_actor_email'), ['actor_email'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_actor_id'), ['actor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_created_at'), ['created_at'], unique=False)
        batch_op.create_index('ix_audit_logs_entity', ['entity_type', 'entity_id'], unique=False)
        batch_op.create_index('ix_audit_logs_request', ['request_id'], unique=False)

    op.create_table('export_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('batch_id', sa.String(length=36), nullable=True),
    sa.Column('batch_name', sa.String(length=255), nullable=True),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.Column('format', sa.Enum('xlsx', 'csv', 'json', 'zip', 'report', name='export_format', native_enum=False, length=40), nullable=False),
    sa.Column('status', sa.Enum('pending', 'running', 'completed', 'failed', name='export_status', native_enum=False, length=40), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('storage_path', sa.String(length=1000), nullable=True),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('byte_size', sa.Integer(), nullable=True),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('row_count', sa.Integer(), nullable=False),
    sa.Column('include_images', sa.Boolean(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('detail', sa.JSON(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('requested_at', UTCDateTime(timezone=True), nullable=True),
    sa.Column('completed_at', UTCDateTime(timezone=True), nullable=True),
    sa.Column('expires_at', UTCDateTime(timezone=True), nullable=True),
    sa.Column('created_at', UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_export_history_created_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_export_history'))
    )
    with op.batch_alter_table('export_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_export_history_batch_id'), ['batch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_export_history_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_export_history_created_by_id'), ['created_by_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_export_history_job_id'), ['job_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_export_history_status'), ['status'], unique=False)

    op.create_table('processing_jobs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_type', sa.Enum('ingest_excel', 'process_batch', 'process_material', 'retry_failed', 'export_batch', 'prune_cache', name='job_type', native_enum=False, length=40), nullable=False),
    sa.Column('status', sa.Enum('queued', 'running', 'paused', 'succeeded', 'partially_succeeded', 'failed', 'cancelled', name='job_status', native_enum=False, length=40), nullable=False),
    sa.Column('batch_id', sa.String(length=36), nullable=True),
    sa.Column('batch_name', sa.String(length=255), nullable=True),
    sa.Column('material_id', sa.Integer(), nullable=True),
    sa.Column('parent_job_id', sa.Integer(), nullable=True),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('total_items', sa.Integer(), nullable=False),
    sa.Column('processed_items', sa.Integer(), nullable=False),
    sa.Column('succeeded_items', sa.Integer(), nullable=False),
    sa.Column('failed_items', sa.Integer(), nullable=False),
    sa.Column('skipped_items', sa.Integer(), nullable=False),
    sa.Column('cancel_requested', sa.Boolean(), nullable=False),
    sa.Column('pause_requested', sa.Boolean(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('worker_id', sa.String(length=120), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('error_type', sa.String(length=120), nullable=True),
    sa.Column('queued_at', UTCDateTime(timezone=True), nullable=True),
    sa.Column('started_at', UTCDateTime(timezone=True), nullable=True),
    sa.Column('finished_at', UTCDateTime(timezone=True), nullable=True),
    sa.Column('heartbeat_at', UTCDateTime(timezone=True), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_processing_jobs_created_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], name=op.f('fk_processing_jobs_material_id_materials'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_job_id'], ['processing_jobs.id'], name=op.f('fk_processing_jobs_parent_job_id_processing_jobs'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_processing_jobs'))
    )
    with op.batch_alter_table('processing_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_processing_jobs_batch_id'), ['batch_id'], unique=False)
        batch_op.create_index('ix_processing_jobs_batch_type', ['batch_id', 'job_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_processing_jobs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_processing_jobs_created_by_id'), ['created_by_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_processing_jobs_job_type'), ['job_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_processing_jobs_material_id'), ['material_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_processing_jobs_status'), ['status'], unique=False)
        batch_op.create_index('ix_processing_jobs_status_queued', ['status', 'queued_at'], unique=False)

    op.create_table('search_results',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('manufacturer_id', sa.Integer(), nullable=True),
    sa.Column('provider', sa.String(length=60), nullable=False),
    sa.Column('provider_kind', sa.Enum('manufacturer', 'distributor', 'marketplace', 'web_search', 'image_search', 'internal', name='provider_kind', native_enum=False, length=40), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('result_score', sa.Float(), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('snippet', sa.Text(), nullable=True),
    sa.Column('page_url', sa.String(length=2000), nullable=True),
    sa.Column('image_url', sa.String(length=2000), nullable=True),
    sa.Column('thumbnail_url', sa.String(length=2000), nullable=True),
    sa.Column('source_domain', sa.String(length=255), nullable=True),
    sa.Column('image_url_hash', sa.String(length=64), nullable=True),
    sa.Column('raw', sa.JSON(), nullable=False),
    sa.Column('is_selected', sa.Boolean(), nullable=False),
    sa.Column('rejection_reason', sa.String(length=60), nullable=True),
    sa.Column('searched_at', UTCDateTime(timezone=True), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['manufacturer_id'], ['manufacturers.id'], name=op.f('fk_search_results_manufacturer_id_manufacturers'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], name=op.f('fk_search_results_material_id_materials'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_search_results'))
    )
    with op.batch_alter_table('search_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_search_results_created_at'), ['created_at'], unique=False)
        batch_op.create_index('ix_search_results_image_url_hash', ['image_url_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_search_results_manufacturer_id'), ['manufacturer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_search_results_material_id'), ['material_id'], unique=False)
        batch_op.create_index('ix_search_results_material_provider', ['material_id', 'provider'], unique=False)
        batch_op.create_index(batch_op.f('ix_search_results_provider'), ['provider'], unique=False)
        batch_op.create_index(batch_op.f('ix_search_results_source_domain'), ['source_domain'], unique=False)

    op.create_table('images',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('search_result_id', sa.Integer(), nullable=True),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=True),
    sa.Column('storage_backend', sa.String(length=20), nullable=False),
    sa.Column('storage_path', sa.String(length=1000), nullable=False),
    sa.Column('library_path', sa.String(length=1000), nullable=True),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('extension', sa.String(length=10), nullable=True),
    sa.Column('byte_size', sa.Integer(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('phash', sa.String(length=128), nullable=True),
    sa.Column('source_url_hash', sa.String(length=64), nullable=True),
    sa.Column('source_url', sa.String(length=2000), nullable=True),
    sa.Column('source_domain', sa.String(length=255), nullable=True),
    sa.Column('source_page_url', sa.String(length=2000), nullable=True),
    sa.Column('status', sa.Enum('candidate', 'downloaded', 'accepted', 'rejected', 'duplicate', 'error', name='image_status', native_enum=False, length=40), nullable=False),
    sa.Column('rejection_reason', sa.Enum('thumbnail', 'watermark', 'too_small', 'duplicate_hash', 'duplicate_perceptual', 'unsupported_type', 'download_failed', 'ocr_mismatch', 'vision_rejected', 'low_confidence', 'broken_image', 'manual', name='rejection_reason', native_enum=False, length=40), nullable=True),
    sa.Column('rejection_detail', sa.Text(), nullable=True),
    sa.Column('is_thumbnail', sa.Boolean(), nullable=False),
    sa.Column('has_watermark', sa.Boolean(), nullable=False),
    sa.Column('ocr_text', sa.Text(), nullable=True),
    sa.Column('ocr_match_score', sa.Float(), nullable=True),
    sa.Column('ocr_engine', sa.String(length=60), nullable=True),
    sa.Column('ocr_tokens', sa.JSON(), nullable=True),
    sa.Column('vision_verified', sa.Boolean(), nullable=True),
    sa.Column('vision_notes', sa.Text(), nullable=True),
    sa.Column('vision_model', sa.String(length=80), nullable=True),
    sa.Column('vision_payload', sa.JSON(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('is_accepted', sa.Boolean(), nullable=False),
    sa.Column('fetched_at', UTCDateTime(timezone=True), nullable=True),
    sa.Column('verified_at', UTCDateTime(timezone=True), nullable=True),
    sa.Column('created_at', UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], name=op.f('fk_images_material_id_materials'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['search_result_id'], ['search_results.id'], name=op.f('fk_images_search_result_id_search_results'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_images'))
    )
    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_images_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_images_is_accepted'), ['is_accepted'], unique=False)
        batch_op.create_index(batch_op.f('ix_images_material_id'), ['material_id'], unique=False)
        batch_op.create_index('ix_images_material_status', ['material_id', 'status'], unique=False)
        batch_op.create_index('ix_images_phash', ['phash'], unique=False)
        batch_op.create_index(batch_op.f('ix_images_search_result_id'), ['search_result_id'], unique=False)
        batch_op.create_index('ix_images_sha256', ['sha256'], unique=False)
        batch_op.create_index('ix_images_source_url_hash', ['source_url_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_images_status'), ['status'], unique=False)

    op.create_table('confidence_scores',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('image_id', sa.Integer(), nullable=True),
    sa.Column('overall', sa.Float(), nullable=False),
    sa.Column('band', sa.Enum('high', 'medium', 'low', 'none', name='confidence_band', native_enum=False, length=40), nullable=False),
    sa.Column('decision', sa.Enum('auto_accept', 'review', 'reject', name='score_decision', native_enum=False, length=40), nullable=False),
    sa.Column('ocr_score', sa.Float(), nullable=True),
    sa.Column('vision_score', sa.Float(), nullable=True),
    sa.Column('brand_score', sa.Float(), nullable=True),
    sa.Column('model_score', sa.Float(), nullable=True),
    sa.Column('text_score', sa.Float(), nullable=True),
    sa.Column('provider_score', sa.Float(), nullable=True),
    sa.Column('weights', sa.JSON(), nullable=False),
    sa.Column('contributions', sa.JSON(), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('strategy', sa.String(length=60), nullable=False),
    sa.Column('missing_signals', sa.JSON(), nullable=True),
    sa.Column('created_at', UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['image_id'], ['images.id'], name=op.f('fk_confidence_scores_image_id_images'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], name=op.f('fk_confidence_scores_material_id_materials'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_confidence_scores'))
    )
    with op.batch_alter_table('confidence_scores', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_confidence_scores_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_confidence_scores_decision'), ['decision'], unique=False)
        batch_op.create_index(batch_op.f('ix_confidence_scores_image_id'), ['image_id'], unique=False)
        batch_op.create_index('ix_confidence_scores_material_decision', ['material_id', 'decision'], unique=False)
        batch_op.create_index(batch_op.f('ix_confidence_scores_material_id'), ['material_id'], unique=False)
        batch_op.create_index('ix_confidence_scores_overall', ['overall'], unique=False)

    op.create_table('duplicates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('image_id', sa.Integer(), nullable=False),
    sa.Column('duplicate_of_image_id', sa.Integer(), nullable=False),
    sa.Column('method', sa.Enum('sha256', 'perceptual_hash', 'source_url', 'manual', name='duplicate_method', native_enum=False, length=40), nullable=False),
    sa.Column('similarity', sa.Float(), nullable=False),
    sa.Column('detail', sa.String(length=500), nullable=True),
    sa.Column('created_at', UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['duplicate_of_image_id'], ['images.id'], name=op.f('fk_duplicates_duplicate_of_image_id_images'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['image_id'], ['images.id'], name=op.f('fk_duplicates_image_id_images'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], name=op.f('fk_duplicates_material_id_materials'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_duplicates'))
    )
    with op.batch_alter_table('duplicates', schema=None) as batch_op:
        batch_op.create_index('ix_duplicates_canonical', ['duplicate_of_image_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_duplicates_created_at'), ['created_at'], unique=False)
        batch_op.create_index('ix_duplicates_image', ['image_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_duplicates_material_id'), ['material_id'], unique=False)

    op.create_table('image_library',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=True),
    sa.Column('image_id', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(length=120), nullable=False),
    sa.Column('library_path', sa.String(length=1000), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('byte_size', sa.Integer(), nullable=True),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('material_code', sa.String(length=120), nullable=True),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('source_url', sa.String(length=2000), nullable=True),
    sa.Column('source_domain', sa.String(length=255), nullable=True),
    sa.Column('created_at', UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['image_id'], ['images.id'], name=op.f('fk_image_library_image_id_images'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_image_library'))
    )
    with op.batch_alter_table('image_library', schema=None) as batch_op:
        batch_op.create_index('ix_image_library_category', ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_image_library_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_image_library_image_id'), ['image_id'], unique=False)
        batch_op.create_index('ix_image_library_material', ['material_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_image_library_material_id'), ['material_id'], unique=False)
        batch_op.create_index('ix_image_library_path', ['library_path'], unique=False)
        batch_op.create_index(batch_op.f('ix_image_library_sha256'), ['sha256'], unique=False)

    op.create_table('review_queue',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('image_id', sa.Integer(), nullable=True),
    sa.Column('reason', sa.Enum('low_confidence', 'ambiguous_match', 'no_candidate', 'conflicting_evidence', 'ocr_mismatch', 'doubtful_source', 'manual_request', name='review_reason', native_enum=False, length=40), nullable=False),
    sa.Column('status', sa.Enum('pending', 'in_progress', 'approved', 'rejected', 'escalated', 'auto_resolved', name='review_status', native_enum=False, length=40), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('assigned_to_id', sa.Integer(), nullable=True),
    sa.Column('reviewer_id', sa.Integer(), nullable=True),
    sa.Column('reviewer_notes', sa.Text(), nullable=True),
    sa.Column('selected_image_id', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', UTCDateTime(timezone=True), nullable=True),
    sa.Column('created_at', UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to_id'], ['users.id'], name=op.f('fk_review_queue_assigned_to_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['image_id'], ['images.id'], name=op.f('fk_review_queue_image_id_images'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], name=op.f('fk_review_queue_material_id_materials'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], name=op.f('fk_review_queue_reviewer_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_review_queue'))
    )
    with op.batch_alter_table('review_queue', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_review_queue_assigned_to_id'), ['assigned_to_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_review_queue_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_review_queue_image_id'), ['image_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_review_queue_material_id'), ['material_id'], unique=False)
        batch_op.create_index('ix_review_queue_material_status', ['material_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_review_queue_reason'), ['reason'], unique=False)
        batch_op.create_index(batch_op.f('ix_review_queue_reviewer_id'), ['reviewer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_review_queue_status'), ['status'], unique=False)
        batch_op.create_index('ix_review_queue_status_priority', ['status', 'priority'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review_queue', schema=None) as batch_op:
        batch_op.drop_index('ix_review_queue_status_priority')
        batch_op.drop_index(batch_op.f('ix_review_queue_status'))
        batch_op.drop_index(batch_op.f('ix_review_queue_reviewer_id'))
        batch_op.drop_index(batch_op.f('ix_review_queue_reason'))
        batch_op.drop_index('ix_review_queue_material_status')
        batch_op.drop_index(batch_op.f('ix_review_queue_material_id'))
        batch_op.drop_index(batch_op.f('ix_review_queue_image_id'))
        batch_op.drop_index(batch_op.f('ix_review_queue_created_at'))
        batch_op.drop_index(batch_op.f('ix_review_queue_assigned_to_id'))

    op.drop_table('review_queue')
    with op.batch_alter_table('image_library', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_image_library_sha256'))
        batch_op.drop_index('ix_image_library_path')
        batch_op.drop_index(batch_op.f('ix_image_library_material_id'))
        batch_op.drop_index('ix_image_library_material')
        batch_op.drop_index(batch_op.f('ix_image_library_image_id'))
        batch_op.drop_index(batch_op.f('ix_image_library_created_at'))
        batch_op.drop_index('ix_image_library_category')

    op.drop_table('image_library')
    with op.batch_alter_table('duplicates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_duplicates_material_id'))
        batch_op.drop_index('ix_duplicates_image')
        batch_op.drop_index(batch_op.f('ix_duplicates_created_at'))
        batch_op.drop_index('ix_duplicates_canonical')

    op.drop_table('duplicates')
    with op.batch_alter_table('confidence_scores', schema=None) as batch_op:
        batch_op.drop_index('ix_confidence_scores_overall')
        batch_op.drop_index(batch_op.f('ix_confidence_scores_material_id'))
        batch_op.drop_index('ix_confidence_scores_material_decision')
        batch_op.drop_index(batch_op.f('ix_confidence_scores_image_id'))
        batch_op.drop_index(batch_op.f('ix_confidence_scores_decision'))
        batch_op.drop_index(batch_op.f('ix_confidence_scores_created_at'))

    op.drop_table('confidence_scores')
    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_images_status'))
        batch_op.drop_index('ix_images_source_url_hash')
        batch_op.drop_index('ix_images_sha256')
        batch_op.drop_index(batch_op.f('ix_images_search_result_id'))
        batch_op.drop_index('ix_images_phash')
        batch_op.drop_index('ix_images_material_status')
        batch_op.drop_index(batch_op.f('ix_images_material_id'))
        batch_op.drop_index(batch_op.f('ix_images_is_accepted'))
        batch_op.drop_index(batch_op.f('ix_images_created_at'))

    op.drop_table('images')
    with op.batch_alter_table('search_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_search_results_source_domain'))
        batch_op.drop_index(batch_op.f('ix_search_results_provider'))
        batch_op.drop_index('ix_search_results_material_provider')
        batch_op.drop_index(batch_op.f('ix_search_results_material_id'))
        batch_op.drop_index(batch_op.f('ix_search_results_manufacturer_id'))
        batch_op.drop_index('ix_search_results_image_url_hash')
        batch_op.drop_index(batch_op.f('ix_search_results_created_at'))

    op.drop_table('search_results')
    with op.batch_alter_table('processing_jobs', schema=None) as batch_op:
        batch_op.drop_index('ix_processing_jobs_status_queued')
        batch_op.drop_index(batch_op.f('ix_processing_jobs_status'))
        batch_op.drop_index(batch_op.f('ix_processing_jobs_material_id'))
        batch_op.drop_index(batch_op.f('ix_processing_jobs_job_type'))
        batch_op.drop_index(batch_op.f('ix_processing_jobs_created_by_id'))
        batch_op.drop_index(batch_op.f('ix_processing_jobs_created_at'))
        batch_op.drop_index('ix_processing_jobs_batch_type')
        batch_op.drop_index(batch_op.f('ix_processing_jobs_batch_id'))

    op.drop_table('processing_jobs')
    with op.batch_alter_table('export_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_export_history_status'))
        batch_op.drop_index(batch_op.f('ix_export_history_job_id'))
        batch_op.drop_index(batch_op.f('ix_export_history_created_by_id'))
        batch_op.drop_index(batch_op.f('ix_export_history_created_at'))
        batch_op.drop_index(batch_op.f('ix_export_history_batch_id'))

    op.drop_table('export_history')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index('ix_audit_logs_request')
        batch_op.drop_index('ix_audit_logs_entity')
        batch_op.drop_index(batch_op.f('ix_audit_logs_created_at'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_actor_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_actor_email'))
        batch_op.drop_index('ix_audit_logs_action_created')
        batch_op.drop_index(batch_op.f('ix_audit_logs_action'))

    op.drop_table('audit_logs')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_created_at'))

    op.drop_table('users')
    with op.batch_alter_table('provider_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_provider_history_started_at'))
        batch_op.drop_index('ix_provider_history_provider_started')
        batch_op.drop_index(batch_op.f('ix_provider_history_provider'))
        batch_op.drop_index('ix_provider_history_outcome')
        batch_op.drop_index(batch_op.f('ix_provider_history_material_id'))
        batch_op.drop_index('ix_provider_history_material')
        batch_op.drop_index(batch_op.f('ix_provider_history_job_id'))
        batch_op.drop_index(batch_op.f('ix_provider_history_created_at'))

    op.drop_table('provider_history')
    with op.batch_alter_table('processing_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_processing_logs_timestamp'))
        batch_op.drop_index(batch_op.f('ix_processing_logs_request_id'))
        batch_op.drop_index(batch_op.f('ix_processing_logs_material_id'))
        batch_op.drop_index('ix_processing_logs_material')
        batch_op.drop_index('ix_processing_logs_level_created')
        batch_op.drop_index(batch_op.f('ix_processing_logs_level'))
        batch_op.drop_index(batch_op.f('ix_processing_logs_job_id'))
        batch_op.drop_index('ix_processing_logs_job_created')
        batch_op.drop_index(batch_op.f('ix_processing_logs_created_at'))
        batch_op.drop_index(batch_op.f('ix_processing_logs_batch_id'))
        batch_op.drop_index('ix_processing_logs_batch')

    op.drop_table('processing_logs')
    with op.batch_alter_table('materials', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_materials_status'))
        batch_op.drop_index('ix_materials_search_query_hash')
        batch_op.drop_index('ix_materials_material_code')
        batch_op.drop_index(batch_op.f('ix_materials_job_id'))
        batch_op.drop_index(batch_op.f('ix_materials_created_at'))
        batch_op.drop_index(batch_op.f('ix_materials_category'))
        batch_op.drop_index('ix_materials_batch_status')
        batch_op.drop_index(batch_op.f('ix_materials_batch_id'))
        batch_op.drop_index(batch_op.f('ix_materials_accepted_image_id'))

    op.drop_table('materials')
    with op.batch_alter_table('manufacturers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_manufacturers_created_at'))

    op.drop_table('manufacturers')
    # ### end Alembic commands ###
